
services:
  database:
    container_name: postgres
    image: 'bitnami/postgresql:14'
    ports:
      - '5432:5432'
    environment:
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=brain-ag-db

  server:
    container_name: brain-ag
    build: .
    restart: always
    ports:
      - 3000:3000
    environment:
      - DATABASE_URL=postgresql://docker:docker@database:5432/brain-ag-db
    depends_on:
      database:
        condition: service_started
    command: 
      - npm 
      - run
      - start:migrate:prod
